/* SIC 2007 division names (2-digit prefix -> official division title),
 * from the ONS SIC 2007 structure. Navigational labels only — the raw
 * codes stay visible everywhere; nothing here is a financial fact.
 * Covers the divisions present in the mandate universe. */
window.__SIC_DIVISIONS__ = {
  "01": "Crop and animal production",
  "18": "Printing and reproduction",
  "20": "Chemicals and chemical products",
  "24": "Manufacture of basic metals",
  "25": "Fabricated metal products",
  "26": "Computer, electronic and optical products",
  "27": "Electrical equipment",
  "28": "Machinery and equipment",
  "29": "Motor vehicles and trailers",
  "33": "Repair and installation of machinery",
  "41": "Construction of buildings",
  "42": "Civil engineering",
  "43": "Specialised construction activities",
  "46": "Wholesale trade",
  "47": "Retail trade",
  "50": "Water transport",
  "53": "Postal and courier activities",
  "55": "Accommodation",
  "56": "Food and beverage service",
  "58": "Publishing activities",
  "59": "Film, video and TV production",
  "61": "Telecommunications",
  "62": "Computer programming and consultancy",
  "63": "Information service activities",
  "64": "Financial service activities",
  "68": "Real estate activities",
  "70": "Head offices; management consultancy",
  "71": "Architectural and engineering activities",
  "72": "Scientific research and development",
  "74": "Other professional, scientific and technical",
  "77": "Rental and leasing activities",
  "78": "Employment activities",
  "81": "Services to buildings and landscape",
  "82": "Office administrative and support",
  "85": "Education",
  "86": "Human health activities",
  "87": "Residential care activities",
  "93": "Sports, amusement and recreation",
  "94": "Membership organisations",
  "95": "Repair of computers and personal goods",
  "96": "Other personal service activities",
};
