/* UK SIC 2007 divisions (two-digit prefix → official title). Display
 * vocabulary for the product surface only — the engine's classification
 * logic lives in the Companies House adapter, never here. */
window.__SIC_DIVISIONS__ = {
  "01": "Crop and animal production",
  "02": "Forestry and logging",
  "03": "Fishing and aquaculture",
  "05": "Mining of coal and lignite",
  "06": "Extraction of crude petroleum and gas",
  "07": "Mining of metal ores",
  "08": "Other mining and quarrying",
  "09": "Mining support services",
  "10": "Manufacture of food products",
  "11": "Manufacture of beverages",
  "12": "Manufacture of tobacco products",
  "13": "Manufacture of textiles",
  "14": "Manufacture of wearing apparel",
  "15": "Manufacture of leather products",
  "16": "Manufacture of wood products",
  "17": "Manufacture of paper products",
  "18": "Printing and reproduction of media",
  "19": "Coke and refined petroleum products",
  "20": "Manufacture of chemicals",
  "21": "Pharmaceutical products",
  "22": "Rubber and plastic products",
  "23": "Other non-metallic mineral products",
  "24": "Manufacture of basic metals",
  "25": "Fabricated metal products",
  "26": "Computer, electronic and optical products",
  "27": "Electrical equipment",
  "28": "Machinery and equipment",
  "29": "Motor vehicles and trailers",
  "30": "Other transport equipment",
  "31": "Manufacture of furniture",
  "32": "Other manufacturing",
  "33": "Repair and installation of machinery",
  "35": "Electricity, gas and steam supply",
  "36": "Water collection and supply",
  "37": "Sewerage",
  "38": "Waste collection and recovery",
  "39": "Remediation services",
  "41": "Construction of buildings",
  "42": "Civil engineering",
  "43": "Specialised construction activities",
  "45": "Motor vehicle sale and repair",
  "46": "Wholesale trade",
  "47": "Retail trade",
  "49": "Land transport and pipelines",
  "50": "Water transport",
  "51": "Air transport",
  "52": "Warehousing and transport support",
  "53": "Postal and courier activities",
  "55": "Accommodation",
  "56": "Food and beverage service",
  "58": "Publishing activities",
  "59": "Film, video and TV production",
  "60": "Programming and broadcasting",
  "61": "Telecommunications",
  "62": "Computer programming and consultancy",
  "63": "Information service activities",
  "64": "Financial service activities",
  "65": "Insurance and pension funding",
  "66": "Auxiliary financial services",
  "68": "Real estate activities",
  "69": "Legal and accounting activities",
  "70": "Head offices; management consultancy",
  "71": "Architectural and engineering activities",
  "72": "Scientific research and development",
  "73": "Advertising and market research",
  "74": "Other professional, scientific and technical",
  "75": "Veterinary activities",
  "77": "Rental and leasing activities",
  "78": "Employment activities",
  "79": "Travel agency and tour operators",
  "80": "Security and investigation",
  "81": "Services to buildings and landscape",
  "82": "Office administrative and support",
  "84": "Public administration and defence",
  "85": "Education",
  "86": "Human health activities",
  "87": "Residential care",
  "88": "Social work without accommodation",
  "90": "Creative, arts and entertainment",
  "91": "Libraries, archives and museums",
  "92": "Gambling and betting",
  "93": "Sports, amusement and recreation",
  "94": "Membership organisations",
  "95": "Repair of computers and personal goods",
  "96": "Other personal service activities",
  "97": "Households as employers",
  "98": "Undifferentiated household production",
  "99": "Extraterritorial organisations",
};
