#!/usr/bin/env bash
# Live API surface verification — scripted version of
# docs/live-api-verification.md. Requires CH_API_KEY in the environment
# and jq. Writes a numbered report plus raw responses into $1 (default:
# out/). Individual step failures are recorded, not fatal — an honest
# partial report beats a silent abort.

set -u
OUT="${1:-out}"
mkdir -p "$OUT"
CH="https://api.company-information.service.gov.uk"
REPORT="$OUT/report.md"
: > "$REPORT"

say() { echo "$*" >> "$REPORT"; }
get() { # get <name> <url> [extra curl args...]
  local name="$1" url="$2"; shift 2
  local code
  code=$(curl -sS -m 30 -D "$OUT/$name.headers" -u "$CH_API_KEY:" "$@" -o "$OUT/$name.json" -w '%{http_code}' "$url" 2>>"$OUT/errors.log" || echo "curl-failed")
  echo "$code"
}
jqr() { jq -r "$2" "$OUT/$1.json" 2>/dev/null || echo "(unparseable)"; }

say "# Live API verification report"
say ""
say "Generated by scripts/verify_live_api.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
say ""

# ---- R1: auth smoke + large filer profile --------------------------------
code=$(get r1 "$CH/company/00445790")
say "## R1 — auth + Tesco PLC profile: HTTP $code"
say '```'
grep -i '^x-ratelimit' "$OUT/r1.headers" >> "$REPORT" || say "(no X-Ratelimit headers)"
say '```'
say "- type: $(jqr r1 .type) | jurisdiction: $(jqr r1 .jurisdiction)"
say "- sic_codes: $(jqr r1 '.sic_codes | join(", ")')"
say "- accounts object:"
say '```json'
jqr r1 .accounts >> "$REPORT"
say '```'
say "- links keys: $(jqr r1 '.links | keys | join(", ")')"
say ""

# ---- R2: advanced search --------------------------------------------------
code=$(get r2 "$CH/advanced-search/companies?sic_codes=62012&company_status=active&size=25")
say "## R2 — advanced search (SIC 62012, active, size=25): HTTP $code"
say "- hits: $(jqr r2 .hits)"
say "- items[0] keys: $(jqr r2 '.items[0] | keys | join(", ")')"
say "- items[0..2]:"
say '```json'
jqr r2 '.items[0:3]' >> "$REPORT"
say '```'
say ""

# ---- R3: find SMALLCO and FULLCO -----------------------------------------
SMALLCO="" ; FULLCO="" ; tries=0
say "## R3 — probe companies"
for num in $(jqr r2 '.items[].company_number'); do
  [ -n "$SMALLCO" ] && [ -n "$FULLCO" ] && break
  [ "$tries" -ge 15 ] && break
  tries=$((tries+1))
  code=$(get "r3_$num" "$CH/company/$num")
  atype=$(jqr "r3_$num" '.accounts.last_accounts.type // "none"')
  say "- $num -> HTTP $code, last_accounts.type=$atype"
  case "$atype" in
    micro-entity|total-exemption-full|total-exemption-small|small|unaudited-abridged)
      [ -z "$SMALLCO" ] && SMALLCO="$num" ;;
    full|medium|group)
      [ -z "$FULLCO" ] && FULLCO="$num" ;;
  esac
  sleep 0.4
done
[ -z "$FULLCO" ] && FULLCO="00445790" && say "- no full filer in sample; falling back to 00445790"
say "- SMALLCO=$SMALLCO FULLCO=$FULLCO (profiles tried: $tries)"
if [ -n "$SMALLCO" ]; then
  say "- SMALLCO last_accounts:"; say '```json'; jqr "r3_$SMALLCO" .accounts.last_accounts >> "$REPORT"; say '```'
fi
say "- FULLCO last_accounts:"; say '```json'; jqr "r3_$FULLCO" '.accounts.last_accounts // empty' >> "$REPORT"; say '```'
say ""

# ---- R4: officers ---------------------------------------------------------
TARGET="${SMALLCO:-$FULLCO}"
code=$(get r4 "$CH/company/$TARGET/officers?items_per_page=100")
say "## R4 — officers ($TARGET): HTTP $code"
say "- total_results: $(jqr r4 .total_results) active_count: $(jqr r4 .active_count)"
say "- items[0] keys: $(jqr r4 '.items[0] | keys | join(", ")')"
say "- items[0].date_of_birth: $(jqr r4 '.items[0].date_of_birth // "absent"')"
code2=$(get r4b "$CH/company/$TARGET/officers?items_per_page=200")
say "- items_per_page=200 -> HTTP $code2, echoed items_per_page: $(jqr r4b .items_per_page)"
say ""

# ---- R5: beneficial owners / PSC -----------------------------------------
code=$(get r5 "$CH/company/$TARGET/persons-with-significant-control")
say "## R5 — PSC ($TARGET): HTTP $code"
say "- kinds: $(jqr r5 '[.items[].kind] | unique | join(", ")')"
say "- natures_of_control (verbatim): $(jqr r5 '[.items[].natures_of_control[]] | unique | join(" | ")')"
say '```json'
jqr r5 '.items' >> "$REPORT"
say '```'
code2=$(get r5s "$CH/company/$TARGET/persons-with-significant-control-statements")
say "- statements: HTTP $code2, values: $(jqr r5s '[.items[].statement] | unique | join(" | ")')"
say ""

# ---- R6: filing history (FULLCO accounts) --------------------------------
code=$(get r6 "$CH/company/$FULLCO/filing-history?category=accounts&items_per_page=10")
say "## R6 — filing history ($FULLCO, accounts): HTTP $code"
say "- total_count: $(jqr r6 .total_count)"
say "- items[0] keys: $(jqr r6 '.items[0] | keys | join(", ")')"
say "- type values: $(jqr r6 '[.items[].type] | unique | join(", ")')"
say "- example transaction_id: $(jqr r6 .items[0].transaction_id)"
DOCMETA=$(jqr r6 '.items[0].links.document_metadata // empty')
say "- links.document_metadata (verbatim): $DOCMETA"
say '```json'
jqr r6 '.items[0]' >> "$REPORT"
say '```'
say ""

# ---- R7 + R8: document metadata and content (FULLCO) ---------------------
fetch_document() { # fetch_document <label> <docmeta_url> <outfile>
  local label="$1" meta="$2" outfile="$3"
  if [ -z "$meta" ] || [ "$meta" = "null" ]; then
    say "## $label — no document_metadata link available; SKIPPED"
    return
  fi
  local code loc code_b code_c
  code=$(get "${label}_meta" "$meta")
  say "## $label — document metadata: HTTP $code"
  say "- resources (verbatim):"
  say '```json'
  jqr "${label}_meta" .resources >> "$REPORT"
  say '```'
  curl -sS -m 30 -D "$OUT/${label}_302.headers" -u "$CH_API_KEY:" \
    -H "Accept: application/xhtml+xml" -o /dev/null "$meta/content" 2>>"$OUT/errors.log"
  loc=$(grep -i '^location:' "$OUT/${label}_302.headers" | tr -d '\r' | awk '{print $2}' | head -1)
  say "- /content redirect Location host: $(echo "$loc" | awk -F/ '{print $3}')"
  if [ -n "$loc" ]; then
    code_b=$(curl -sS -m 60 -o "$OUT/$outfile" -w '%{http_code}' "$loc" 2>>"$OUT/errors.log" || echo curl-failed)
    say "- manual follow WITHOUT auth: HTTP $code_b; first 200 chars:"
    say '```'
    head -c 200 "$OUT/$outfile" >> "$REPORT" 2>/dev/null; say ""
    say '```'
  fi
  code_c=$(curl -sSL -m 60 -u "$CH_API_KEY:" -H "Accept: application/xhtml+xml" \
    -o /dev/null -w '%{http_code}' "$meta/content" 2>>"$OUT/errors.log" || echo curl-failed)
  say "- one-shot -L WITH auth forwarded: HTTP $code_c (documents the double-auth behaviour)"
  say ""
}
fetch_document "R7R8-fullco" "$DOCMETA" "fullco-accounts.xhtml"

# ---- R9: same for SMALLCO -------------------------------------------------
if [ -n "$SMALLCO" ]; then
  code=$(get r9 "$CH/company/$SMALLCO/filing-history?category=accounts&items_per_page=5")
  SDOCMETA=$(jqr r9 '.items[0].links.document_metadata // empty')
  say "## R9 — SMALLCO ($SMALLCO) accounts filing: HTTP $code, document_metadata: $SDOCMETA"
  fetch_document "R9-smallco" "$SDOCMETA" "smallco-accounts.xhtml"
else
  say "## R9 — SKIPPED: no SMALLCO found in the R2 sample"
fi

# ---- R10: charges ---------------------------------------------------------
code=$(get r10 "$CH/company/00445790/charges?items_per_page=5")
say "## R10 — charges (00445790): HTTP $code"
say "- envelope keys (verbatim): $(jqr r10 'keys | join(", ")')"
say "- items[0] keys: $(jqr r10 '.items[0] | keys | join(", ")')"
say '```json'
jqr r10 '.items[0]' >> "$REPORT"
say '```'
say ""

# ---- R11: exemptions ------------------------------------------------------
code=$(get r11 "$CH/company/00445790/exemptions")
say "## R11 — exemptions (00445790): HTTP $code"
if [ "$code" = "200" ]; then say '```json'; jqr r11 . >> "$REPORT"; say '```'; fi
say ""

say "---"
say "Errors log (curl-level, if any):"
say '```'
cat "$OUT/errors.log" >> "$REPORT" 2>/dev/null || say "(none)"
say '```'

echo "Report written to $REPORT"
